/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Booking = IDL.Record({
  'serviceType' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'patientName' : IDL.Text,
  'submissionTime' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'submitBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'serviceType' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'patientName' : IDL.Text,
    'submissionTime' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'submitBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };